//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocioSindicato.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Socio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Socio()
        {
            this.Conyuge = new HashSet<Conyuge>();
            this.Hijo = new HashSet<Hijo>();
        }
    
        public string rut_socio { get; set; }
        public byte[] imagen { get; set; }
        public string nombre_socio { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public int id_categoria { get; set; }
        public string tipo_contrato { get; set; }
        public int id_planta { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public int edad { get; set; }
        public string domicilio { get; set; }
        public string estado_civil { get; set; }
        public int telefono { get; set; }
        public string nacionalidad { get; set; }
        public string correo { get; set; }
        public string datos_papa { get; set; }
        public string datos_mama { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conyuge> Conyuge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hijo> Hijo { get; set; }
        public virtual Planta Planta { get; set; }
    }
}
